In [6]:
#Q1
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    return numpy.array(arr,float)

arr = input().strip().split(' ')

1 2 3 4 -8 -10


In [22]:
#Q2
import numpy as np
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
#Q3
import numpy 
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print(array.transpose())
print(array.flatten())

2 2
1 2
2 3
[[1 2]
 [2 3]]
[1 2 2 3]


In [3]:
#Q4
import numpy 
n, m,p = map(int, input().split())

array = numpy.array([input().strip().split() for _ in range(n+m)], int)
print(numpy.concatenate(array).reshape(m+n,p))



4 3 2
4 3
1 2
3 4
3 4
5 6
1 2
3 2
[[4 3]
 [1 2]
 [3 4]
 [3 4]
 [5 6]
 [1 2]
 [3 2]]


In [21]:
#Q5
import numpy 
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))


2 2
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [22]:
#Q6
import numpy
numpy.set_printoptions(legacy = '1.13')
n,m = map(int, input().split())
print(numpy.eye(n,m))


2 2
[[ 1.  0.]
 [ 0.  1.]]


In [28]:
#Q7
import numpy as np
n,m = map(int,input().split())

a=np.zeros((n,m),int)
b=np.zeros((n,m),int)
for i in range(n):
    a[i]=np.array(input().split(),int)
for i in range(n):
    b[i]=np.array(input().split(),int)  

print(a+b)
print(a-b)
print(a*b)
print(np.array(a/b,int))
print(a%b)
print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [29]:
#Q8
import numpy
numpy.set_printoptions(legacy = '1.13')
arr = numpy.array(input().split(),dtype = float)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [30]:
#Q8
import numpy
n, m = map(int, input().split())
arr = numpy.array([input().split() for _ in range(n)],int)
print(numpy.prod(numpy.sum(arr, axis=0), axis=0))



2 2 
1 2
3 4
24


In [34]:
#Q9
import numpy
n, m = map(int, input().split())
arr = numpy.array([input().split() for _ in range(n)],int)
print(numpy.max(numpy.min(arr, axis=1), axis=None))




2 2
1 5
4 1
1


In [37]:
#Q10
import numpy
numpy.set_printoptions(legacy='1.13')
n,m = map(int,input().split())
my_array = numpy.array([input().split() for _ in range(n)],dtype = float)
print(numpy.mean(my_array, axis = 1))
print(numpy.var(my_array, axis = 0))
print(numpy.std(my_array, axis = None))


2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [39]:
#Q11
import numpy
n=int(input())
arr1,arr2=[(numpy.array([list(map(int,input().split())) for _ in range(n)])) for _ in range(2)]
print (numpy.dot(arr1,arr2))


1
5 
4
[[20]]


In [40]:
#Q12
import numpy
a = numpy.array(input().split(),int)
b = numpy.array(input().split(),int)
print(numpy.inner(a, b))
print(numpy.outer(a, b))



1 2
3 4
11
[[3 4]
 [6 8]]


In [41]:
#Q13
import numpy
print(numpy.polyval(list(map(float,input().split())),float(input())))

1.1 2 3
0
3.0


In [43]:
#Q14
import numpy

print(round(numpy.linalg.det(numpy.array([input().split() for _ in range(int(input()))],float)),2))

2
1.1 1.1
1.1 1.1
0.0
